services:
  app:
    build: .
    ports:
      - "8443:8443"
      - "8000:8000"
    volumes:
      - C:/Users/jdman/.originalcoin:/root/.originalcoin
    environment:
      - ORIGINALCOIN_NETWORK_PORT=8443
      - ORIGINALCOIN_DOMAIN=localhost
      - ORIGINALCOIN_USE_ACME=false
      - PG_PASSWORD=+Pw=fku123!
      - DOCKERIZED=true
      - PYTHONUNBUFFERED=1 # Force unbuffered output
    command: [ "python", "-u", "originalcoin.py", "--host", "0.0.0.0" ] # -u for unbuffered
    depends_on:
      - postgres
    networks:
      - originalcoin-net
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=originalcoin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=+Pw=fku123!
    ports:
      - "5432:5432"
    networks:
      - originalcoin-net
networks:
  originalcoin-net:
volumes:
  pgdata:
